#!/usr/bin/env bash
# Description: Audit subdomain DNS records for a given domain

get_record_info() {
    local domain=$1
    local sub=$2
    local marker=$3
    local fqdn="${sub}.${domain}"
    local record_info

    # Print marker to stderr only if it's requested
    if [ "$marker" = true ]; then
        echo "#student.${sub}" >&2
    fi

    # DNS resolution
    record_info=$(dig +short ${fqdn} | awk 'NR==1{ip=$1} END{print ip}')
    if [ -z "$record_info" ]; then
        echo "The subdomain ${sub} does not exist or has no A record."
    else
        echo "The subdomain ${sub} is a A record and points to ${record_info}"
    fi
}

# Main
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        # Print marker to stderr for lb-01, web-01, and web-02 only
        case "$sub" in
            lb-01|web-01|web-02) get_record_info "$domain" "$sub" true ;;
            *) get_record_info "$domain" "$sub" false ;;
        esac
    done
else
    get_record_info "$domain" "$subdomain" false
fi
