#!/usr/bin/env bash
# Description: Audit subdomain DNS records for a given domain
# Usage: ./audit_dns.sh example.com [subdomain]

get_record_info() {
    local domain=$1
    local sub=$2
    local fqdn="${sub}.${domain}"
    local record_info

    record_info=$(dig +short ${fqdn} | awk 'NR==1{ip=$1} END{print ip}')
    if [ -z "$record_info" ]; then
        echo "The subdomain ${sub} does not exist or has no A record."
    else
        echo "The subdomain ${sub} is an A record and points to ${record_info}"
    fi
}

# Main
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_record_info "$domain" "$sub"
    done
else
    get_record_info "$domain" "$subdomain"
fi
